### ISSUE TITLE
IP address not showing up

### ISSUE THREAD

**Issue by JohnFFlanagan** [DIY-Machines/Smart-Model-Steam-Train#2]
The IP address is printed as 0.0.0.0
I believe you want WiFi.softAPIP() as opposed toWIFi.localIP()
With that my ESP32 prints 192.168.4.1 but that may be network specific based on other existing addresses.

**Comment by robboz4** [comment]
I had the same issue and changed the line to:
Serial.println(WiFi.softAPIP());

This printed out 192.168.4.1 on the debug console from the Arduino IDE.

I successfully connected to the AP and used a browser with this address and the camera and buttons came straight away.

**Comment by JohnFFlanagan** [comment]
This issue is fixed by the pull request (not mine) as well as parameterizing AP vs non-AP mode.

**Comment by DIY-Machines** [comment]
I have merged the pull request. Thank you for verifying it as a solution.
